version: '2'
services:
    postgredb:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=baswara
            - POSTGRES_PASSWORD=Password1!
        volumes:
            - ./postgreVolume:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    mongodb:
        image: mongo:3.6.3
        environment:
            - MONGO_INITDB_ROOT_USERNAME=baswara
            - MONGO_INITDB_ROOT_PASSWORD=password123!
        ports:
            - 27017:27017
        volumes:
            - ./mongoVolume:/data/db/

    uaa-app:
        image: uaa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgredb:5432/uaa
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=loot1234
            
    gateway-app:
        image: gateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgredb:5432/gateway
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=loot1234
        ports:
            - 8090:8080
    
    generic-app:
        image: generic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=generic
            - SPRING_DATA_MONGODB_USERNAME=baswara
            - SPRING_DATA_MONGODB_PASSWORD=password123!
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=loot1234
        volumes:
            - ./files:/files
            - ./reports:/reports
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
